apiVersion: fission.io/v1
kind: Package
metadata:
  creationTimestamp: null
  name: hellojs-e4485d5e-0752-42ca-8c37-d123655f9f66
  namespace: default
spec:
  deployment:
    checksum:
      sum: 1a24906213d5713450fb2a883615d8bfe1f4b48f369d228b438127a298160934
      type: sha256
    type: url
    url: https://raw.githubusercontent.com/fission/fission/master/examples/nodejs/hello.js
  environment:
    name: nodejs
    namespace: default
  source:
    checksum: {}
status:
  buildstatus: none
  lastUpdateTimestamp: "2021-04-14T13:52:37Z"

---
apiVersion: fission.io/v1
kind: Function
metadata:
  creationTimestamp: null
  name: hellojs
  namespace: default
spec:
  InvokeStrategy:
    ExecutionStrategy:
      ExecutorType: poolmgr
      MaxScale: 0
      MinScale: 0
      SpecializationTimeout: 120
      TargetCPUPercent: 0
    StrategyType: execution
  concurrency: 5
  configmaps: null
  environment:
    name: nodejs
    namespace: default
  functionTimeout: 60
  idletimeout: 120
  package:
    packageref:
      name: hellojs-e4485d5e-0752-42ca-8c37-d123655f9f66
      namespace: default
  resources: {}
  secrets: null
